# Learn more from ready-to-use templates: https://www.gitpod.io/docs/introduction/getting-started/quickstart

# List the start up tasks. Learn more: https://www.gitpod.io/docs/configure/workspaces/tasks
tasks:
  - name: 0_General
    before: |
      printf 'export PATH="$HOME%s:$PATH"\n' "/.astra/cli" >> $HOME/.bashrc
      printf 'unset JAVA_TOOL_OPTIONS\n' >> $HOME/.bashrc
      curl -Ls "https://dtsx.io/get-astra-cli" | bash >> ./install.log
    init: | 
      mkdir /workspace/data-pipelines/tools
      cd /workspace/data-pipelines/tools
      wget https://github.com/datastax/pulsar/releases/download/ls210_4.0/lunastreaming-2.10.4.0-bin.tar.gz \
          && tar zxf lunastreaming-2.10.4.0-bin.tar.gz >> ./install.log \
          && rm -f lunastreaming-2.10.4.0-bin.tar.gz
      mkdir lunastreaming-2.10.4.0/connectors
      cd lunastreaming-2.10.4.0/connectors
      wget -O pulsar-io-file-2.10.3.nar "https://www.apache.org/dyn/mirrors/mirrors.cgi?action=download&filename=pulsar/pulsar-2.10.3/connectors/pulsar-io-file-2.10.3.nar"
      cd /workspace/data-pipelines
      chmod 750 mvnw
        
      clear
    command: |
      source /home/gitpod/.astra/cli/astra-init.sh
      clear
      echo -e "\n\n   *** Workshop ready... Let's go ! ***\n"
      gp open README.md
#      gp preview --external https://astra.dev/yt-9-14
#      astra setup

  - name: 1_File_Connector
    command: |
      unset JAVA_TOOL_OPTIONS
      source /home/gitpod/.astra/cli/astra-init.sh
      cd /workspace/data-pipelines/tools/lunastreaming-2.10.4.0/bin
      clear
      echo "***************"
      echo "** File Connector ***"
      echo "***************"

  - name: 2_Consumer_stocks-in
    command: |
      unset JAVA_TOOL_OPTIONS
      source /home/gitpod/.astra/cli/astra-init.sh
      cd /workspace/data-pipelines/tools/lunastreaming-2.10.4.0/bin
      clear
      echo "***************"
      echo "** Client Stocks In ***"
      echo "***************"

  - name: 3_Consumer_stocks-enriched
    command: |
      unset JAVA_TOOL_OPTIONS
      source /home/gitpod/.astra/cli/astra-init.sh
      cd /workspace/data-pipelines/tools/lunastreaming-2.10.4.0/bin
      clear
      echo "***************"
      echo "** Client Stocks Enriched ***"
      echo "***************"

  - name: 4_Consumer_cdc-data
    command: |
      unset JAVA_TOOL_OPTIONS
      source /home/gitpod/.astra/cli/astra-init.sh
      cd /workspace/data-pipelines/tools/lunastreaming-2.10.4.0/bin
      clear
      echo "***************"
      echo "** Client CDC Data ***"
      echo "***************"

  - name: 5_Consumer_stocks-aapl
    command: |
      unset JAVA_TOOL_OPTIONS
      source /home/gitpod/.astra/cli/astra-init.sh
      cd /workspace/data-pipelines/tools/lunastreaming-2.10.4.0/bin
      clear
      echo "***************"
      echo "** Client Stocks AAPL ***"
      echo "***************"




            
ports:
  - port: 8080
    onOpen: open-browser
    visibility: public
  
github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: false
    addCheck: true
    addComment: false
    addBadge: true
    addLabel: false
